### ISSUE TITLE
conda forge packages

### ISSUE THREAD

**Issue by Meyenhofer** [hadim/scijava-jupyter-kernel#34]
Hi @hadim 

really excited about this work of yours. 
Just checked if I manage to install the kernel. But the `conda install scijava-jupyter-kernel` did not manage to pull it from the conda-forge. I checked on the website and could not find the package indeed.

**Comment by hadim** [comment]
Hi,

Sorry I have edited the README to remove the warning message saying that the conda package is not ready yet because the conda-forge PR was merged : https://github.com/conda-forge/staged-recipes/pull/2841 . But it looks like the package has not been uploaded yet.

It will be probably soon.

I'll ping you here to let you know.

**Comment by hadim** [comment]
Small update here : 

- OSX package is on conda and **should** work. I say should because I don't a Mac to test. Se please tell me if it's working for you guys.

- Windows package is on conda but <i have a small issue running the install command of the kernel : that should be fixed soon.

- Of course Linux build is broken... I am investigating with the conda-forge devs what's happening.

**Comment by hadim** [comment]
Recipe repo is here https://github.com/conda-forge/scijava-jupyter-kernel-feedstock FYI

**Comment by imagejan** [comment]
@hadim is it supposed to work with both Python 2.7 and Python3 ?

I tried on Mac OSX: the install seems to work fine withou errors, but running `jupyter kernelspec list` gives just the python-3 kernel (or python-2 on a different system), no other.

**Comment by Meyenhofer** [comment]
same here. Was able to install the package. but then it is not automaticall added to the kernel list. So I added it
```
jupyter kernelspec install /.../opt/scijava-jupyther-kernel --user
```
But then it still does not appear in the list `jupyter kernelspec list`. Then I had a look in the 
`/Users/${USER}/Library/Jupyter/kernels/scijava-jupyter-kernel`. In there there are is the entire arsenal of the jar-files. But I could not find a `kernel.json` file anywhere.

**Comment by hadim** [comment]
@imagejan the kernel does not need Python itself. Python is only used by Jupyter to communicate with the kernel and execute the client (console or notebook). So as long as Jupyter support Python 2 and 3, it's fine.

At the end of the installation do you log showing that kernel is correctly installed such as `scijava-python`, `scijava-groovy` etc?

The command runs to install the kernel is here: https://github.com/conda-forge/scijava-jupyter-kernel-feedstock/blob/master/recipe/post-link.sh. You can try it (you need to be in the Conda environment where the kernel has been installed).

@Meyenhofer the `kernel.json` file is not supposed to be installed in `/Users/${USER}/Library/Jupyter/kernels/scijava-jupyter-kernel` but rather in you local config. In Linux it's `$HOME/.local/share/jupyter/kernels`:

```bash
$ ls $HOME/.local/share/jupyter/kernels
scijava-clojure  scijava-groovy  scijava-java  scijava-javascript  scijava-python  scijava-r  scijava-ruby  scijava-scala
```

**Comment by imagejan** [comment]
> you need to be in the Conda environment where the kernel has been installed

Oh, you need to be in an *environment*! 🙂 I tried without any environment before, and didn't get the scijava-kernel log messages (but no errors either). Sorry, I'm a conda/python noob.

After creating a new environment:
```
conda create --name scijava
```
I was able to install scijava-jupyter-kernel and the kernels are listed. I can select them from Jupyter Lab, but when starting a new notebook, it shows *Starting kernel* forever in the top right corner...

**Comment by hadim** [comment]
Well installation should also work on the root conda env. I guess that is another bug :-)

Jupyterlab is not working for now (see #21). Try jupyter notebook.

**Comment by imagejan** [comment]
> Try jupyter notebook.

Yay, it's working on Mac! 😄 Thanks!

----

On Windows, I get errors like:
```
[ERROR] C:\Anaconda3\python.exe does not seem to be a valid Python executable.
[ERROR] Output :
[ERROR] Error : Python 2.7.13 :: Anaconda 4.3.1 (64-bit)
```
I guess this is what you meant when saying there is a small issue still, right?

**Comment by hadim** [comment]
Happy to see the Mac installation is working.

Yeah, Windows kernel installation is fucked up at the moment.

Still working on the Linux package too.

**Comment by hadim** [comment]
I am seeing the end of the nightmare.

- Linux package is working. Tested on a fresh installed Ubuntu + fresh Anaconda, both in root and custom environment.

- I except the OSX package to behave the same as the Linux one because the code to build the package is the same. But it needs to be tested : `conda install scijava-jupyter-kernel` (version should be `0.2.2-3`.

- Windows package is broken, I am working on it.

**Comment by imagejan** [comment]
👍 version 0.2.2-3 is working on OSX

**Comment by hadim** [comment]
Alleluia !

**Comment by hadim** [comment]
I am almost done with the Windows version.

**Comment by hadim** [comment]
I got the Windows build. The package should be uploaded in few hours (Appveyor builds are super slow to start).

**Comment by hadim** [comment]
Finally, all the builds work and the packages have been uploaded to https://anaconda.org/conda-forge/scijava-jupyter-kernel/files

I have tested the conda package on a fresh Windows 10 installation and it works.

**Comment by Meyenhofer** [comment]
I was struggling a bit with the environment. I use `pyenv` which I find a convenient way to manage python distributions on OsX. Using the `conda` commands for environments on top of it did not seem to do any good. Following your instructions did not work for me. Changing the line to activate the environment to `source activate scijava` (activate instead of install) just closed the terminal window. 
So here is what I did instead:
```
brew install pyenv pyenv-virtualenv
# Set the paths according to the pyenv docs
pyenv install anaconda3-4.3.1
pyenv local anaconda3-4.3.1
pyenv virutualenv scijava
pyenv activate scijava
conda install openjdk
conda install scijva-jupyter-kernel
```

**Comment by hadim** [comment]
Anaconda is much more than a Python package, it's a Python distribution that should not be installed within any environment in my opinion.

Conda packages are also very specific to Anaconda and do a lot of magic under-the-hood to make things just work.

In consequence, I would strongly suggest you install Anaconda system wide and use as your default Python distribution (usually it's better to not work from the default Python that comes with your system. It's a good practice to have a strict separation between both to avoid any potential critical system issue).

About `pyenv`, I don't know it so I can't help you but I guess the error is related to the fact you are using Anaconda within a `pyenv` environment.

I am sorry for the inconvenience but after years of Python usage, I found that Anaconda is the only way to distribute cross-platform out-of-the-box packages containing not just Python code (Java, C, C++, etc).

Ultimately I would like to provide a graphical installer that installs Miniconda (an Anaconda light version) + the scijava jupyter kernel.
